name: chrono
description: Date and time library that strictly adheres to ISO 8601 ISO 8601
version: 0.0.1
uploader: Denis Portnov <denixport@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
  benchmark_harness: ^2.0.0
